version: '3.3'

services:
  # MySQL - Dev
  node-starter-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: lollerskates
      MYSQL_DATABASE: node-starter
      MYSQL_USER: node-starter
      MYSQL_PASSWORD: node-starter
    ports:
      - '3309:3306'
    container_name: node-starter-mysql

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - .:/usr/data
    ports:
      - 27017:27017

  node-starter:
    build: .
    command: yarn start
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/app
    depends_on:
      - node-starter-mysql
